name: "🚀 Releaser"

on:
  push:
    tags: "*"

env:
  PYTHON_VERSION: 3.7


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python requirements
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/packaging.txt

    #- name: Compile selected files to bytecode and stage them
    #  run: |
    #    python -OO -m compileall -b -i .compile
    #    git add --force ./\*.pyc

    - name : Get current changelog for ${GITHUB_REF/refs\/tags\//}
      run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: release.md

    - name: Deploy plugin
      run: >-
        qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --github-token ${{ secrets.GITHUB_TOKEN }}
        --allow-uncommitted-changes
        --create-plugin-repo
